name: Build Android

on:
  push:
    branches:
      - master # or main
    # Change according to your needs
    paths:
      - "android/"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: |
          npm run build
          npm run export

      - name: Capacitor update
        run: |
          npx cap sync
          npx cap update

      - name: Capacitor copy
        run: npx cap copy

      - name: Build app bundle
        run: |
          cd android && gradle bundle && chmod +x gradlew && ./gradlew assembleRelease
          tree app/build/outputs/

      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: Notes
      #     tag_name: v1.0.0  # Increment as needed
      #     prerelease: false
      #     files: |
      #       android/app/build/outputs/apk/release/app-release.apk
      #       android/app/build/outputs/bundle/release/app-release.aab
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #   env:
      #     GITHUB_REPOSITORY: <your repo name here. Eg: dhzdhd/notes>
